common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from pybo import views
from rest_framework import routers
from pybo.views import MovieViewSet
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

router = routers.DefaultRouter() 
router.register('movies',MovieViewSet) # prefix = movies , viewset = MovieViewSet

urlpatterns = [
    path("pybo/", include('pybo.urls')),
    #path('pybo/', include('allauth.urls')),
    path('pybo/',include('django.contrib.auth.urls')),
    #path('accounts/',include('django.contrib.auth.urls')),
    #path('accounts/',include('allauth.urls')),
    #re_path(r'^admin/', admin.site.urls),
    re_path(r'^api/',include(router.urls)),
    path("admin/", admin.site.urls),
    
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pybo/urls.py
from django.urls import path
from pybo.views import MovieViewSet
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path, include, re_path
app_name = 'pybo'

urlpatterns = [
    #path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    #path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('change-password/',auth_views.PasswordChangeView.as_view()),    
    path('answer/vote/<int:answer_id>/', views.answer_vote, name='answer_vote'),
    path('question/vote/<int:question_id>/', views.question_vote, name='question_vote'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    #path('question/create/', views.question_create, name='question_create'),
    path('profile/base/', views.user_profile, name='user_profile'),
    path('profile/question/', views.user_question, name='user_question'),
    path('profile/answer/', views.user_answer, name='user_answer'),
    path('profile/comment/', views.user_comment, name='user_comment'),
    path('password_reset/', views.UserPasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done/', views.UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    path('alexander/', views.index2, name='index2'),
    path('question/craete/<str:category_name>/', views.question_create, name='question_create'),
    path('question/list/', views.index, name='index'),
    path('question/list/<str:category_name>/', views.index, name='index'),
    path('question/detail/<int:question_id>/', views.detail, name='detail'),
]

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
    
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->

{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
{% load static %}
<link rel="stylesheet" type="text/css" href="static/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="../static/style.css">



<div class="hero">

    <nav>
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

        </button>
        <div id="navbarSupportedContent">
            <ul>
                <li>
                    {% if user.is_authenticated %}


                    <img src="{%static 'img/user.png' %}" onclick="toggleMenu()" class="user-pic" width="118px" />

                    <div class="sub-menu-wrap" id="subMenu">
                        <div class="sub-menu">

                            <div class="user-info">
                                <img src="{%static 'img/user.png' %}">
                                <h3>{{ user.username }}</h3>
                            </div>

                            <hr>

                            <a href="#" class="sub-menu-link">
                                <img src="{%static 'img/profile.png' %}">
                                <p>edit profile</p>
                                <span>></span>
                            </a>
                            <a href="{% url 'pybo:user_profile' %}" class="sub-menu-link">
                                <img src="{%static 'img/setting.png' %}">
                                <p>setting profile</p>
                                <span> > </span>
                            </a>
                            <a href="#" class="sub-menu-link">
                                <img src="{%static 'img/help.png' %}">
                                <p>help & surport</p>
                                <span> > </span>
                            </a>
                            <a href="{% url 'common:logout' %}" class="sub-menu-link">
                                <img src="{%static 'img/logout.png' %}">
                                <p>logout</p>
                                <span> > </span>
                            </a>

                        </div>
                    </div>


                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'pybo:index' %}">질문&답변</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'pybo:index2' %}">알렉산더 사진</a>-->
<!--                </li>-->
            </ul>

    </div>
</nav>
</div>

<script>
    let subMenu = document.getElementById("subMenu");

    function toggleMenu(){
        subMenu.classList.toggle("open-menu");
        console.log("dssddsds");
    }
</script>

templates/password_reset.html
<div class="container" id="wc-container" style="user-select: auto;">

    <div class="row mobile-only" style="user-select: auto;">
        <div class="col-12" style="text-align: center; margin-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 50px; width: 100%; user-select: auto;">
            <h3 class="feature-heading mb-2 heading_mention pc-only" style="user-select: auto;"></h3>
        </div>
    </div>

    <div class="row" id="main_row" style="user-select: auto;">

        <div class="col-lg-8 offset-lg-2 col-xl-4 offset-xl-4" style="padding: 0px; user-select: auto;">

            <div id="main_heading" style="padding-left: 10px;width: 90%; margin-left: 4.5%; padding-right: 10px;background-color: rgba(255, 255, 255, 0.87);user-select: auto; border-radius: 1rem; box-shadow: 0 0 15px 1px rgb(0 0 0 / 40%); ">

                <div class="row" style="padding-top: 2rem; user-select: auto;">
                    <div class="col-md-12 mb-3" style="text-align: center; user-select: auto;">

                        <h3 class="pc-only"  style="height: 25px; margin-bottom: 15px; user-select: auto;">DOG AND CAT</h3>

                        <form method="post" action="{% url 'password_reset' %}" style="width: 100%;">
                            <div>
                            {% csrf_token %}
<!--                            {{ form.as_p }}-->
                                <input placeholder="Email" type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email" style="user-select: auto;
                                        width:40%;background-color: white; height: 5%;margin-bottom: 15px;  ">
                            </div>
                            <button type="submit"
                                    style="cursor: pointer; width: 20%; height: 5%; padding:6px 15px; border-radius: 5px; outline: none; border: none; background: #0F3758; color: white">
                                send Email
                            </button>
                        </form>
                    </div>
                    <div class="col-md-12" style="user-select: auto;"></div>
                </div>
                <div style="user-select: auto;">
                    <div class="row" style="text-align: center; user-select: auto; " >
                        <div class="col-md-12" style="padding-left: 15px;padding-top: 50px; padding-right: 15px; user-select: auto;">
                            <p style="user-select: auto;">
                                <a href="https://e20f-121-134-166-70.jp.ngrok.io/pybo/password_reset/" style="user-select: auto;">비밀번호를 잊으셨나요? </a>
                            </p>
                        </div>
                        <div class="col-md-12" id="footer_login" style="padding-left: 0px; padding-right: 0px; user-select: auto;">
                            <p style="margin-top: 8px; user-select: auto;">아직 dog and cat 회원이 아니신가요?
                                <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                            </p>
                        </div>
                    </div>
                    <hr style="margin-top: 0px; user-select: auto;">
                    <p class="company-copyright" style="text-align: center; margin-top: 20px; padding-bottom: 40px; user-select: auto;">AssembleCircle Corporation © 2022 </p>
                </div>
            </div>
        </div>
    </div>
</div>

templates/password_reset_done_fail.html
<html><head></head><body><div class="container" id="wc-container" style="user-select: auto;">

    <div class="row mobile-only" style="user-select: auto;">
        <div class="col-12" style="text-align: center; margin-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 50px; width: 100%; user-select: auto;">
            <h3 class="feature-heading mb-2 heading_mention pc-only" style="user-select: auto;"></h3>
        </div>
    </div>

    <div class="row" id="main_row" style="user-select: auto;">

        <div class="col-lg-8 offset-lg-2 col-xl-4 offset-xl-4" style="padding: 0px; user-select: auto;">

            <div id="main_heading" style="padding-left: 10px;width: 90%; margin-left: 4.5%; padding-right: 10px;background-color: rgba(255, 255, 255, 0.87);user-select: auto; border-radius: 1rem; box-shadow: 0 0 15px 1px rgb(0 0 0 / 40%); ">

                <div class="row" style="padding-top: 2rem; user-select: auto;">
                    <div class="col-md-12 mb-3" style="text-align: center; user-select: auto;">

                        <h3 class="pc-only" style="height: 25px; margin-bottom: 15px; user-select: auto;">DOG AND CAT</h3>

                        <form method="post" action="/pybo/password_reset/" style="width: 100%;">
                            <div>
                            <input type="hidden" name="csrfmiddlewaretoken" value="7fYKeSJnAACGBBioyOHm9HNfoCPgpfN0j3tSoV0xnXUcLbLw4X9gcljIAy66LTcO">
<!--                            <p>
    <label for="id_email">Email:</label>
    <input type="email" name="email" autocomplete="email" maxlength="254" required id="id_email">
    
    
      
    
  </p>-->
                                <input placeholder="Email" type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email" style="user-select: auto;
                                        width:40%;background-color: white; height: 5%;margin-bottom: 15px;  ">
                            </div>
                            <button type="submit" style="cursor: pointer; width: 20%; height: 5%; padding:6px 15px; border-radius: 5px; outline: none; border: none; background: #0F3758; color: white">
                                send Email
                            </button>
                        </form>
                    </div>
                    <div class="col-md-12" style="user-select: auto;"></div>
                </div>
                
                <div style="user-select: auto;">
                    <div class="row" style="text-align: center; user-select: auto; ">
                        <div class="col-md-12" style="padding-left: 15px; padding-right: 15px; user-select: auto;">
                            <h5 class="email-err" style="height:25px;margin-bottom: 15px;color:red">이메일을 잘못 입력하셨습니다. 다시 입력해주세요.</h5>
                            <p style="user-select: auto;">
                                <a href="https://e20f-121-134-166-70.jp.ngrok.io/pybo/password_reset/" style="user-select: auto;">비밀번호를 잊으셨나요? </a>
                            </p>
                        </div>
                        <div class="col-md-12" id="footer_login" style="padding-left: 0px; padding-right: 0px; user-select: auto;">
                            <p style="margin-top: 8px; user-select: auto;">아직 dog and cat 회원이 아니신가요?
                                <a class="nav-link" href="/common/signup/">회원가입</a>
                            </p>
                        </div>
                    </div>
                    <hr style="margin-top: 0px; user-select: auto;">
                    <p class="company-copyright" style="text-align: center; margin-top: 20px; padding-bottom: 40px; user-select: auto;">AssembleCircle Corporation © 2022 </p>
                </div>
            </div>
        </div>
    </div>
</div>







</body></html>

templates/password_rest_done.html
{% extends "base.html" %}
{% block content %}
<div class="row pt-6" style="user-select: auto;">
    <div class="col-12 text-center py-5" style="user-select: auto; text-align: center; padding-top: 4.5rem;">
        <h1 class="my-5 py-5" style="user-select:auto; font-size: 3.5rem;">메일 보냄 ㅅㄱ</h1>
        <p style="user-select: auto;">메일 빨리 확인좀</p>
    </div>
</div>
{% endblock %}